### ISSUE TITLE
Initial Home screen design

### ISSUE THREAD

**Issue by obasille** [GameWithPixels/pixels-js#12]
Step 1:
Show a list of pixels with their basic info and active profile

Step 2:
Differentiate "scanned pixels" and "paired pixels".
Add ability to pair with a scanned Pixel.

**Comment by obasille** [comment]
Pixel detailed page:
* Rename
* Blink
* Change Profile (selectable list of available profiles)
* Stats histogram (image)
* Advanced
  - Calibrate
  - Reset Settings
  - Reboot
* Forget (= unpair)

**Comment by jeansimonet** [comment]
More fun statistics:
- Times rolled (this session/lifetime)
- Hours used (this session/lifetime)

**Comment by obasille** [comment]
Change requests:
* Remove "More Profiles +", instead add "More" card at the end of the recent profiles list
* Show "Upload" button when selecting another profile in "recent profiles" list
* When tapping on, more have panel that slides up with list of profiles (like action sheet)
* Change "Apply" profile to "Upload", grey out button if current profile is selected
* Show upload message box
* Remove roll status
* Add "session / all" toggle for stats

**Comment by jeansimonet** [comment]
Other suggestions:
- Flash Storage use, like the iPhone storage summary
![image](https://user-images.githubusercontent.com/8626854/202861562-8623f77a-7933-41c1-b10a-af7f8df9ca66.png)
Categories could be:
- Patterns
- Rules
- Statistics
