### ISSUE TITLE
update r-n-nordic-nrf5-dfu on npm

### ISSUE THREAD

**Issue by owav** [GameWithPixels/pixels-js#66]
Hi,

The current version of r-n-nordic-nrf5-dfu on [NPM](https://www.npmjs.com/package/@systemic-games/react-native-nordic-nrf5-dfu) is one year old and doesn't support Android 14 / sdk 34.

Is the current github version of the lib expected to be published on NPM any time soon ?

Thanks

**Comment by obasille** [comment]
Hi @owav!
Yes I can publish an updated version later this week.
May I ask what kind of app you are using the library for?

**Comment by owav** [comment]
Thanks !

I use it to flash firmwares on a nRF52 chip for an electronic lock.
I initially used Pilloxa's [react-native-nordic-dfu](https://github.com/Pilloxa/react-native-nordic-dfu), then some fork to make it compatible with newer Android versions, but I found your lib to have better performance.

It's a cool project you have here btw :)

**Comment by obasille** [comment]
Hi @owav!
I've published v1.3 on NPM, it's the latest from the main branch (of a few days ago).
Sorry the delay!
I'm quite happy that someone outside of our company is using the library, please let me know if you run in any trouble :)
